### ISSUE TITLE
Build failed trying 'npm start' or 'npm run build'

### ISSUE THREAD

**Issue by katan** [xdan/jodit#148]
**Jodit Version:**  3.2.38

**Code**

```ts
ERROR in ./src/langs/en.ts
Module build failed (from ./src/utils/lang-loader.js):
D:\proyects\jodit\src\utils\lang-loader.js:43
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at loadLoader (D:\proyects\jodit\node_modules\loader-runner\lib\loadLoader.js:18:17)
    at iteratePitchingLoaders (D:\proyects\jodit\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\proyects\jodit\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (D:\proyects\jodit\node_modules\webpack\lib\NormalModule.js:280:3)
    at NormalModule.build (D:\proyects\jodit\node_modules\webpack\lib\NormalModule.js:427:15)
    at Compilation.buildModule (D:\proyects\jodit\node_modules\webpack\lib\Compilation.js:635:10)
    at factory.create (D:\proyects\jodit\node_modules\webpack\lib\Compilation.js:884:14)
    at factory (D:\proyects\jodit\node_modules\webpack\lib\NormalModuleFactory.js:405:6)
    at hooks.afterResolve.callAsync (D:\proyects\jodit\node_modules\webpack\lib\NormalModuleFactory.js:155:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (D:\proyects\jodit\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at resolver (D:\proyects\jodit\node_modules\webpack\lib\NormalModuleFactory.js:138:29)
    at process.nextTick (D:\proyects\jodit\node_modules\webpack\lib\NormalModuleFactory.js:342:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
 @ ./src/langs/index.ts 17:11-26
 @ ./src/index.ts
 @ multi webpack-hot-middleware/client ./src/index
i ｢wdm｣: Failed to compile.
```

**Expected behavior:**
The build compilation runs without errors.

**Actual behavior:**
Following the steps in the section 'For contributors' on Readme file, the build fails with default packages.

**Comment by xdan** [comment]
Please, check your nodejs version. 
```js
try {
} catch {} // without (e) 
```
works fine in `nodejs 10`
if yow will be make pull request you can add `(e)` in your code

**Comment by katan** [comment]
Hi xdan,
Thanks for answer quickly.

Yes, I'm tryed to fix adding ``` (e)```, but another errors appears.

I'm just upgrade de node version from 8.11.3 to 10.15.1
Now, the previous error is fixed, but the build fails yet:

```ts
ERROR in [at-loader] ./src/langs/index.ts:6:31 
    TS2306: File 'D:/proyects/jodit/src/langs/de.ts' is not a module.

ERROR in [at-loader] ./src/langs/index.ts:7:31 
    TS2306: File 'D:/proyects/jodit/src/langs/fr.ts' is not a module.

ERROR in [at-loader] ./src/langs/index.ts:8:31 
    TS2306: File 'D:/proyects/jodit/src/langs/ru.ts' is not a module.

ERROR in [at-loader] ./src/langs/index.ts:9:31 
    TS2306: File 'D:/proyects/jodit/src/langs/ar.ts' is not a module.

ERROR in [at-loader] ./src/langs/index.ts:10:34 
    TS2306: File 'D:/proyects/jodit/src/langs/zh_cn.ts' is not a module.

ERROR in [at-loader] ./src/langs/index.ts:11:31 
    TS2306: File 'D:/proyects/jodit/src/langs/es.ts' is not a module.

ERROR in [at-loader] ./src/langs/index.ts:12:31 
    TS2306: File 'D:/proyects/jodit/src/langs/nl.ts' is not a module.

ERROR in [at-loader] ./src/langs/index.ts:13:31 
    TS2306: File 'D:/proyects/jodit/src/langs/hu.ts' is not a module.

ERROR in [at-loader] ./src/langs/index.ts:14:31 
    TS2306: File 'D:/proyects/jodit/src/langs/tr.ts' is not a module.

ERROR in [at-loader] ./src/langs/index.ts:15:34 
    TS2306: File 'D:/proyects/jodit/src/langs/pt_br.ts' is not a module.

ERROR in [at-loader] ./src/langs/index.ts:16:31 
    TS2306: File 'D:/proyects/jodit/src/langs/en.ts' is not a module.
i ｢wdm｣: Failed to compile.
```

**Comment by xdan** [comment]
Sorry I misled you, on my machine is nodejs 11.6
Is it possible to install it?

**Comment by katan** [comment]
Thanks xdan,
I'm just installed on a VM and builds correctly (nodejs v11.10).

**Comment by amrita-syn** [comment]
Still getting the issue 
![image](https://user-images.githubusercontent.com/45505551/60584439-e4321780-9daa-11e9-9d8f-000c149adc4d.png)
