### ISSUE TITLE
[Feature request] Clear undo/redo history

### ISSUE THREAD

**Issue by AgentSmith0** [xdan/jodit#792]
**Jodit Version:**  3.15.2

**Browser:**  All
**OS:**  All
**Is React App:**  False

Is there any way to clear the undo/redo history? If not, is it possible to implement this feature?

**Comment by ulfw** [comment]
I have implemented this as an event that is fired externally

```
    editor.events.on('editor.clearHistory', () => {
        editor.observer.stack.clear();
    });
```

**Comment by AgentSmith0** [comment]
Thanks @ulfw, unfortunately, this doesn't work always in my case: When I set the editor value via editor.value, clear the stack, change the editors text to another value and clear the stack again, the undo button still appears, but doesn't do anything.

**Comment by xdan** [comment]
> Thanks @ulfw, unfortunately, this doesn't work always in my case: When I set the editor value via editor.value, clear the stack, change the editors text to another value and clear the stack again, the undo button still appears, but doesn't do anything.

Hm. it is a bug. I'll fix it today

**Comment by xdan** [comment]
@AgentSmith0 
Try that
```js
editor.events.on('editor.clearHistory', () => {
        editor.observer.clear();
});
```

**Comment by AgentSmith0** [comment]
@xdan Hm, still the same problem...

**Comment by ulfw** [comment]
I had the same problem when reloading page with cleared history, but clicking into the editor window disabled the undo/redo buttons. Maybe setting focus to th editor again will solve?

**Comment by xdan** [comment]
@AgentSmith0 @ulfw The Observer module is asynchronous, i.e. it does not process the change immediately, but only processes the last one in n milliseconds. This is done so that, for example, words when you enter them get into the history of changes, and not every letter.
The observer interface does not have methods to hang a handler on a change. I'll think about how best to do it, but for now you can do a little hack

```js
const editor = Jodit.make({
    observer: {
       timeout: 100
    }
});
editor.value = 'test';
editor.async.setTimeout(() => {
     editor.observer.clear();
}, 150);
```

**Comment by xdan** [comment]
Maybe when called
```js
editor.value = 'test1';
editor.value = 'test2';
```
the history handler must be called immediately

**Comment by xdan** [comment]
@ulfw @AgentSmith0 
Look at this release https://github.com/xdan/jodit/releases/tag/3.15.3

**Comment by AgentSmith0** [comment]
Thanks, but it still doesn't work like that:
```
editor.value = "some value";
editor.history.clear();
editor.value = "some value2";
editor.history.clear();
```

Sometimes, the undo button appears...

**Comment by AgentSmith0** [comment]
I seems to fail only when a specific string is set as value before...
I need some time to look at this, but I think it is definitely better than before. It works on every "normal" case.
Thank you very much for the new release!

**Comment by xdan** [comment]
@AgentSmith0 Can you show this specific string?

**Comment by AgentSmith0** [comment]
Sorry, I tested again and the string value is not the problem. It seems to be still a timing problem... I will test this behaviour.

**Comment by AgentSmith0** [comment]
I tried again with version 3.16.1 and it works fine now...
I don't really know the reason for this, but I will keep my eye on it.
Thank you very much!
